[package]
name = "jettester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bpaf = { version = "0.9.19", features = ["derive"] }
gjson = "0.8.1"
jiff = "0.2.5"
url = "2.5.4"
wsclient = { version = "0.1.0", path = "../wsclient" }
