[package]
name = "wsclient"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bytes = "1.10.1"
httparse = "1.10.1"
rand = "0.9.0"
rustls = "0.23.25"
thiserror = "2.0.12"
url = "2.5.4"
webpki-roots = "0.26.8"
